version: '3.5'

volumes:
  mysql-db:

services: 

  mysql:
    image: mysql:8.0.18
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: 'reservation-service'
      MYSQL_USER: 'reservation'
      MYSQL_PASSWORD: 'reservation@123'
      MYSQL_ROOT_PASSWORD: 'root@123'
    ports:
      - "3306:3306"
    networks: 
      - reservation-service-network
    volumes:
      - mysql-db:/var/lib/mysql

networks: 
  reservation-service-network:
