server:
  port: 9000

spring:
  application:
    name: reservation-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation-service?createDatabaseIfNotExist=true&useSSL=true
    username: reservation
    password: reservation@123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIA4DLHBONGD2PGCY7Y
  secretKey: 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
  bucketName: cadastro-cliente