spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:h2:mem:reservationdb
    driverCl: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIA4DLHBONGD2PGCY7Y
  secretKey: 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
  bucketName: cadastro-cliente
  